# Generated by Django 3.2.15 on 2023-04-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Spanish', 'Spanish'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Greek', 'Greek'), ('Italian', 'Italian'), ('Croatian', 'Croatian'), ('Turkish', 'Turkish'), ('French', 'French'), ('Moroccan', 'Moroccan'), ('British', 'British'), ('German', 'German'), ('Austrian', 'Austrian'), ('Lebanese', 'Lebanese'), ('Caribbean', 'Caribbean'), ('Indian', 'Indian'), ('Thai', 'Thai'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese'), ('Mexican', 'Mexican'), ('American', 'American'), ('Other', 'Other')], default='exit', max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
