# Generated by Django 3.2.15 on 2023-04-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230401_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Spanish', 'Spanish'), ('Polish', 'Polish'), ('Portuguese', 'Portuguese'), ('Greek', 'Greek'), ('Italian', 'Italian'), ('Croatian', 'Croatian'), ('Turkish', 'Turkish'), ('French', 'French'), ('Moroccan', 'Moroccan'), ('British', 'British'), ('German', 'German'), ('Lebanese', 'Lebanese'), ('Caribbean', 'Caribbean'), ('Indian', 'Indian'), ('Thai', 'Thai'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese'), ('Mexican', 'Mexican'), ('American', 'American'), ('Other', 'Other')], max_length=50),
        ),
    ]
