# Generated by Django 3.2.15 on 2023-04-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230401_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Quotes', 'Quotes'), ('Animals', 'Animals'), ('Lifestyle', 'Lifestyle'), ('Fun Fact', 'Fun Fact'), ('Creative', 'Creative'), ('Nature', 'Nature'), ('Arts & Entertainmen', 'Arts & Entertainmen'), ('Books', 'Books'), ('Design & Fashion', 'Design & Fashion'), ('Education', 'Education'), ('Food & Beverage', 'Food & Beverage'), ('Health/Beauty', 'Health/Beauty'), ('Sport', 'Sport'), ('Clothing (Brand)', 'Clothing (Brand)'), ('Automotive', 'Automotive'), ('Games/Toys', 'Games/Toys'), ('Musician/Band', 'Musician/Band'), ('Movie', 'Movie'), ('Other', 'Other')], max_length=50),
        ),
    ]
